apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: omero-web
  name: omero-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omero-web
  template: # Pod template
    metadata:
      labels:
        app: omero-web
    spec: # Pod specificiation
      automountServiceAccountToken: false
      securityContext:
        # fsGroup forces volumes to be owned by gid=1000(omero-web)
        # This is necessary for the static files to be copied over
        # runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: omero-web
          image: us-east1-docker.pkg.dev/<GCP PROJECT NAME>/<ARTIFACT REGISTRY REPO>/omero-web:latest
          imagePullPolicy: Always
          env:
            - name: CONFIG_omero_web_server__list
              value: '[["omero-readonly-server", 4064, "omero"]]'
            - name: CONFIG_omero_web_top__logo
              value: '/static/webgateway/img/logo.png'
          #ports:
          #- containerPort: 4080
          #  protocol: TCP
          volumeMounts:
            - name: omero-static
              mountPath: /opt/omero/web/OMERO.web/var
        - name: nginx
          image: nginx:1.21.4
          volumeMounts:
            - mountPath: "/etc/nginx/ssl"
              name: nginx-ssl
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: nginx-configmap
              readOnly: true
            - name: omero-static
              mountPath: /opt/omero-static
              subPath: static
              readOnly: true
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl
        - name: nginx-configmap
          configMap:
            name: nginxconfigmap
        - name: omero-static
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: omero-web
  annotations:
    cloud.google.com/network-tier: Standard
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: omero-web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP