apiVersion: v1
kind: Pod
metadata:
  name: omero-server
spec:
  containers:
    - name: omero-server
      resources:
        limits:
          memory: "7Gi"
          ephemeral-storage: "4Gi"
          cpu: "7000m"
        requests:
          memory: "7Gi"
          ephemeral-storage: "4Gi"
          cpu: "7000m"
      env:
        - name: CONFIG_omero_jvmcfg_percent_blitz
          value: '20'
        - name: CONFIG_omero_jvmcfg_percent_pixeldata
          value: '20'
        - name: CONFIG_omero_jvmcfg_system__memory
          value: '8000'
        - name: CONFIG_omero_db_poolsize
          value: '75'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: omero-readonly-server
spec:
  template:
    spec:
      containers:
        - name: omero-readonly-server
          resources:
            limits:
              memory: "7Gi"
              ephemeral-storage: "4Gi"
              cpu: "7000m"
            requests:
              memory: "7Gi"
              ephemeral-storage: "4Gi"
              cpu: "7000m"
          env:
            - name: CONFIG_omero_jvmcfg_percent_blitz
              value: '20'
            - name: CONFIG_omero_jvmcfg_percent_pixeldata
              value: '20'
            - name: CONFIG_omero_jvmcfg_system__memory
              value: '8000'
            - name: CONFIG_omero_db_poolsize
              value: '75'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: omero-web
spec:
  template:
    spec:
      containers:
        - name: omero-web
          resources:
            limits:
              memory: "2Gi"
              ephemeral-storage: "1Gi"
              cpu: "2000m"
            requests:
              memory: "2Gi"
              ephemeral-storage: "1Gi"
              cpu: "2000m"
          env:
            - name: CONFIG_omero_web_top__logo
              value: '/static/webgateway/img/logo.png'
            - name: CONFIG_omero_web_public_enabled
              value: 'true'
            - name: CONFIG_omero_web_public_user
              valueFrom:
                secretKeyRef:
                  name: omero-web-secrets
                  key: CONFIG_omero_web_public_user
            - name: CONFIG_omero_web_public_password
              valueFrom:
                secretKeyRef:
                  name: omero-web-secrets
                  key: CONFIG_omero_web_public_password
            - name: CONFIG_omero_web_public_url__filter
              value: "^/iviewer|webgateway|api|webclient|gallery"
            - name: CONFIG_omero_web_apps
              value: '["omero_iviewer", "omero_gallery"]'
            - name: CONFIG_omero_web_cors__origin__whitelist
              value: >-
                 ["https://www.ebi.ac.uk", "https://www.mousephenotype.org", "https://www.test-cors.org", "https://dev.mousephenotype.org", "https://beta.mousephenotype.org", "https://data.mousephenotype.org", "https://test.mousephenotype.org", "https://wwwdev.ebi.ac.uk"]
            - name: CONFIG_omero_web_django__additional__settings
              value: >-
                 [["CSP_DEFAULT_SRC", ["'self'", "'unsafe-inline'"]], ["CSP_SCRIPT_SRC", ["'self'", "'unsafe-inline'", "'unsafe-eval'", "blob:"]], ["CSP_IMG_SRC", ["'self'", "data:"]], ["CSP_OBJECT_SRC", ["'self'", "data:"]], ["CSP_MEDIA_SRC", ["'self'", "data:"]], ["CSP_FRAME_ANCESTORS", ["https://www.mousephenotype.org", "https://dev.mousephenotype.org", "https://beta.mousephenotype.org", "https://data.mousephenotype.org", "https://test.mousephenotype.org", "https://wwwdev.ebi.ac.uk", "https://www.ebi.ac.uk"]]]
            - name: CONFIG_omero_web_middleware
              value: >-
                [{"index": 1, "class": "django.middleware.common.BrokenLinkEmailsMiddleware"}, {"index": 2, "class": "django.middleware.common.CommonMiddleware"}, {"index": 3, "class": "django.contrib.sessions.middleware.SessionMiddleware"}, {"index": 4, "class": "django.middleware.csrf.CsrfViewMiddleware"}, {"index": 5, "class": "django.contrib.messages.middleware.MessageMiddleware"}, {"index": 0.5, "class": "whitenoise.middleware.WhiteNoiseMiddleware"}, {"index": 0.4, "class": "corsheaders.middleware.CorsMiddleware"}, {"index": 10, "class": "corsheaders.middleware.CorsPostCsrfMiddleware"}, {"index": 100, "class": "csp.middleware.CSPMiddleware"}]
            - name: CONFIG_omero_web_open__with
              value: >-
                [["Image viewer", "webgateway", {"supported_objects": ["image"], "script_url": "webclient/javascript/ome.openwith_viewer.js"}], ["omero_iviewer", "omero_iviewer_index", {"supported_objects": ["images", "dataset", "well"], "script_url": "omero_iviewer/openwith.js", "label": "OMERO.iviewer"}]]
            - name: CONFIG_omero_web_session__cookie__secure
              value: 'true'
        - name: nginx
          readinessProbe:
            httpGet:
              path: /webclient/login/
              port: 443
              scheme: HTTPS
          resources:
            limits:
              memory: "1Gi"
              ephemeral-storage: "1Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              ephemeral-storage: "1Gi"
              cpu: "1000m"
