apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
  - port: 2049
  selector:
    app: nfs-server

---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  containers:
    - name: nfs-server
      image: itsthenetwork/nfs-server-alpine
      imagePullPolicy: Always
      env:
        - name: SHARED_DIRECTORY
          value: /mountdir
      ports:
      - containerPort: 2049
        protocol: TCP
      volumeMounts:
        - name: mountdir
          mountPath: /mountdir
      securityContext:
        privileged: true
  volumes:
    - name: mountdir
      emptyDir: {}