apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
data:
  nginx.conf: |
    upstream backend {
    server 127.0.0.1:4080;
    }
    server {
        listen 80 default_server;
        server_name localhost;

        location = /healthz {
            #access_log off;
            return 200;
        }
        
        location / {
            proxy_pass http://backend;
        }

        location /static {
            alias /opt/omero-static;
            autoindex off;
        }
    }
  csrf_trusted_origins: '["http://web_url:port"]'