apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: omero-rw-web
  name: omero-rw-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omero-rw-web
  template: # Pod template
    metadata:
      labels:
        app: omero-rw-web
    spec: # Pod specificiation
      automountServiceAccountToken: false
      securityContext:
        # fsGroup forces volumes to be owned by gid=1000(omero-web)
        # This is necessary for the static files to be copied over
        # runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: omero-rw-web
          image: omero-web
          imagePullPolicy: Never
          env:
            - name: CONFIG_omero_web_server__list
              value: '[["omero-server", 4064, "omero"]]'
          #ports:
          #- containerPort: 4080
          #  protocol: TCP
          volumeMounts:
            - name: omero-static-rw
              mountPath: /opt/omero/web/OMERO.web/var
        - name: nginx-rw
          image: nginx:1.21.4
          volumeMounts:
            - mountPath: "/etc/nginx/ssl"
              name: nginx-ssl
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: nginx-configmap-rw
              readOnly: true
            - name: omero-static-rw
              mountPath: /opt/omero-static
              subPath: static
              readOnly: true
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl
        - name: nginx-configmap-rw
          configMap:
            name: nginxconfigmap
        - name: omero-static-rw
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: omero-rw-web
spec:
  type: LoadBalancer
  selector:
    app: omero-rw-web
#   ports:
#   - name: web
#     port: 4080
#     targetPort: 4080
#     protocol: TCP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP 