apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
  - port: 5432
  selector:
    app: database

---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: database
      image: postgres:11
      imagePullPolicy: Always
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: omero-secrets
              key: CONFIG_omero_db_user
        - name: POSTGRES_DB
          value: omero
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: omero-secrets
              key: CONFIG_omero_db_pass
      ports:
      - containerPort: 5432
        protocol: TCP