apiVersion: v1
kind: Pod
metadata:
  name: omero-server
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  containers:
    - name: omero-server
      image: us-east1-docker.pkg.dev/<PROJECT NAME>/omero-repo/omero-server:latest
      env:
        - name: CONFIG_omero_db_name
          value: omero_database
        - name: CONFIG_omero_db_host
          value: <FILESTORE IP>
  volumes:
    - name: files-mount
      nfs: 
        server: <FILESTORE IP>
        path: /mountdir
    - name: data-mount
      nfs: 
        server: <FILESTORE IP>
        path: /mr_mountdir

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: omero-readonly-server
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: omero-readonly-server
          image: us-east1-docker.pkg.dev/<PROJECT NAME>/omero-repo/omero-server:latest
          env:
            - name: CONFIG_omero_db_name
              value: omero_database
            - name: CONFIG_omero_db_host
              value: <FILESTORE IP>
      volumes:
        - name: files-mount
          nfs: 
            server: <FILESTORE IP>
            path: /mountdir
        - name: data-mount
          nfs: 
            server: <FILESTORE IP>
            path: /mr_mountdir

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: omero-web
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: omero-web
          image: us-east1-docker.pkg.dev/<PROJECT NAME>/omero-repo/omero-web:latest

