# Based on https://raw.githubusercontent.com/GoogleCloudPlatform/gke-rbac-demo/master/terraform/modules/instance/manifests/hello-server.yaml

kind: Service
apiVersion: v1
metadata:
  labels:
    app: omero-readonly-server
  name: omero-readonly-server
  annotations:
    # Request an internal IP address: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
    networking.gke.io/load-balancer-type: "External"
spec:
  ports:
  - name: omero
    port: 4063
    protocol: TCP
    targetPort: 4063
  - name: omero-ssl
    port: 4064
    protocol: TCP
    targetPort: 4064

  # Load balance requests across all pods labeled with app=hello-server
  selector:
    app: omero-readonly-server

  # Disable session affinity, each request may be routed to a new pod
  sessionAffinity: None

  # Expose the service internally only
  type: LoadBalancer

---
# Run a vanilla omero server instance
# https://hub.docker.com/r/openmicroscopy/omero-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omero-readonly-server
  labels:
    app: omero-readonly-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omero-readonly-server
  template:
    metadata:
      labels:
        app: omero-readonly-server
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        cloud.google.com/gke-nodepool: <POOL NAME>
      containers:
        - name: omero-readonly-server
          image: <CONTAINER IMAGE>
          imagePullPolicy: Always
          resources:
            limits:
              memory: "7Gi"
              ephemeral-storage: "4Gi"
              cpu: "7000m"
            requests:
              memory: "7Gi"
              ephemeral-storage: "4Gi"
              cpu: "7000m"
          env:
            - name: CONFIG_omero_db_name
              value: <DB NAME>
            - name: CONFIG_omero_db_host
              value: <CLOUD SQL IP>
            - name: CONFIG_omero_data_dir
              value: /OMERO # this is the default
            - name: CONFIG_omero_db_user
              valueFrom:
                secretKeyRef:
                  name: omero-readonly-secrets
                  key: CONFIG_omero_db_user
            - name: CONFIG_omero_db_pass
              valueFrom:
                secretKeyRef:
                  name: omero-readonly-secrets
                  key: CONFIG_omero_db_pass
            - name: CONFIG_omero_jvmcfg_percent_blitz
              value: '20'
            - name: CONFIG_omero_jvmcfg_percent_pixeldata
              value: '20'
            - name: CONFIG_omero_jvmcfg_system__memory
              value: '8000'
            - name: CONFIG_omero_db_poolsize
              value: '75'
            - name: CONFIG_omero_cluster_read__only_db 
              value: 'true'
            - name: CONFIG_omero_cluster_read__only_repo
              value: 'true'
            - name: CONFIG_omero_pixeldata_memoizer_dir_local
              value: /tmp/BioFormatsCache
          ports:
          - containerPort: 4063
            protocol: TCP
          - containerPort: 4064
            protocol: TCP
          volumeMounts:
          - name: files-mount
            mountPath: /OMERO
            readOnly: true
          - name: data-mount
            mountPath: /data_mount
            readOnly: true
      volumes:
        - name: files-mount
          nfs: 
            server: <FILESTORE IP>
            path: <MOUNT PATH>
        - name: data-mount
          nfs: 
            server: <FILESTORE IP>
            path: <DATA MOUNT PATH>