# This workflow will test that the local k8s setup does not error
# This is useful to keep an eye on version incompatibilities

name: Local test
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Start up local kubernetes pods
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          cache: false
      - name: test cluster
        run: kubectl get pods -A
      - name: build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build local_k8s/containers/omero-server -t omero-server
          docker build local_k8s/containers/omero-web -t omero-web
          echo -n "verifying images:"
          docker images
      - name: startup pods
        run: kubectl apply -k local_k8s/test
      - name: sleep for 2 min
        run: sleep 120s
      - name: print pods
        run: kubectl get pods -A
      - name: test servers
        run: |
          kubectl port-forward svc/omero-server 6064:4064 --address='0.0.0.0' &
          kubectl exec omero-server -- bash -c "/opt/omero/server/server_venv/bin/omero login -u root -w omero -s localhost:6064"
          POD=$(kubectl get pod -l app=omero-readonly-server -o jsonpath="{.items[0].metadata.name}"
          kubectl port-forward svc/omero-readonly-server 5064:4064 --address='0.0.0.0' &
          kubectl exec $POD -- bash -c "/opt/omero/server/server_venv/bin/omero login -u root -w omero -s localhost:5064"
      - name: test web
        run: |
          kubectl port-forward svc/omero-web 8080:4080 --address='0.0.0.0' &
          curl -I localhost:8080
